// Jālacitra Edge Traversal Semantics (Part M4, J5-ALG-002)

import type { EdgeKind } from "./edges.ts";

export type TraversalDirection = "forward" | "backward" | "both" | "dependents" | "dependencies";

export interface EdgeSemanticRule {
	forwardMeaning: string;
	backwardMeaning: string;
	impactDirection: "forward" | "backward" | "none";
}

export const EDGE_SEMANTICS: Record<EdgeKind, EdgeSemanticRule> = {
	contains: {
		forwardMeaning: "contains child",
		backwardMeaning: "contained by parent",
		impactDirection: "forward",
	},
	imports: {
		forwardMeaning: "imports module/file",
		backwardMeaning: "imported by file/module",
		impactDirection: "backward", // dependents are files importing this
	},
	declares: {
		forwardMeaning: "declares symbol",
		backwardMeaning: "declared in file",
		impactDirection: "backward",
	},
	exports: {
		forwardMeaning: "exports symbol",
		backwardMeaning: "exported by file",
		impactDirection: "backward",
	},
	references: {
		forwardMeaning: "references symbol",
		backwardMeaning: "referenced by symbol/file",
		impactDirection: "backward", // dependents are those referencing this
	},
	calls: {
		forwardMeaning: "calls callee",
		backwardMeaning: "called by caller",
		impactDirection: "backward", // dependents are callers
	},
	overrides: {
		forwardMeaning: "overrides base method",
		backwardMeaning: "overridden by subtype method",
		impactDirection: "backward", // dependents are overriders
	},
	extends: {
		forwardMeaning: "extends base class/interface",
		backwardMeaning: "extended by subtype",
		impactDirection: "backward", // dependents are subtypes
	},
	configures: {
		forwardMeaning: "configures target",
		backwardMeaning: "configured by key",
		impactDirection: "forward",
	},
	reads_config: {
		forwardMeaning: "reads config key",
		backwardMeaning: "read by symbol/file",
		impactDirection: "backward", // dependents are readers of the config
	},
	generates: {
		forwardMeaning: "generates build artifact/file",
		backwardMeaning: "generated from source target/file",
		impactDirection: "forward", // downstream artifacts generated by this
	},
	builds: {
		forwardMeaning: "builds input file/package",
		backwardMeaning: "built by build target",
		impactDirection: "backward",
	},
	tests: {
		forwardMeaning: "tests subject symbol/file",
		backwardMeaning: "tested by test case/file",
		impactDirection: "backward", // dependents are tests covering this
	},
	depends_on: {
		forwardMeaning: "depends on package/dependency",
		backwardMeaning: "depended upon by package",
		impactDirection: "backward",
	},
	exposes: {
		forwardMeaning: "exposes external contract",
		backwardMeaning: "exposed by unit",
		impactDirection: "forward", // exposing contracts impacted by unit
	},
	consumes: {
		forwardMeaning: "consumes external contract",
		backwardMeaning: "consumed by unit",
		impactDirection: "backward",
	},
	observed_at_runtime: {
		forwardMeaning: "observed runtime relation to target",
		backwardMeaning: "observed runtime relation from subject",
		impactDirection: "backward",
	},
	renamed_from: {
		forwardMeaning: "renamed to new node",
		backwardMeaning: "renamed from old node",
		impactDirection: "none", // excluded from impact analysis by default (J5-EDGE-002)
	},
	source_of: {
		forwardMeaning: "maps to source file",
		backwardMeaning: "source of compiled artifact",
		impactDirection: "backward",
	},
	unresolved_to: {
		forwardMeaning: "unresolved reference to target",
		backwardMeaning: "unresolved target referenced from source",
		impactDirection: "none",
	},
	handled_by: {
		forwardMeaning: "handled by handler symbol",
		backwardMeaning: "handles event",
		impactDirection: "forward",
	},
	rendered_from: {
		forwardMeaning: "rendered from component symbol",
		backwardMeaning: "renders UI element",
		impactDirection: "backward",
	},
};

/**
 * Returns which direction to traverse an edge kind when expanding dependents (impact).
 * For example:
 * - calls: we want callers (dst -> src, backward)
 * - imports: we want importers (dst -> src, backward)
 * - extends: we want subclasses (dst -> src, backward)
 * - tests: we want test cases (dst -> src, backward)
 * - exposes: we want contracts exposed (src -> dst, forward)
 */
export function isDependentHop(kind: EdgeKind, direction: "src_to_dst" | "dst_to_src"): boolean {
	const rule = EDGE_SEMANTICS[kind];
	if (!rule || rule.impactDirection === "none") return false;
	if (rule.impactDirection === "backward" && direction === "dst_to_src") return true;
	if (rule.impactDirection === "forward" && direction === "src_to_dst") return true;
	return false;
}
