import assert from "node:assert/strict";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { classifyFile, isBinaryBuffer } from "../inventory/classify.ts";
import { computeDigest } from "../inventory/digest.ts";
import { enumerateRepository } from "../inventory/enumerate.ts";
import { IgnoreEngine } from "../inventory/ignore.ts";

test("J5-INV-001: Ignore precedence and hard exclusions", () => {
	const padmaignore = `
# Padmaignore rule
ignored_by_padma.ts
!keep_me.ts
`;
	const gitignore = `
# Gitignore rule
ignored_by_git.ts
keep_me.ts
`;
	const engine = new IgnoreEngine(padmaignore, gitignore);

	// 1. Hard exclusions
	assert.equal(engine.evaluate(".git/config", false).reasonCode, "EXCLUDED_VCS_INTERNAL");
	assert.equal(engine.evaluate("node_modules/pkg/index.js", false).reasonCode, "EXCLUDED_DEPENDENCY_DIR");
	assert.equal(engine.evaluate("vendor/bundle/tool", false).reasonCode, "EXCLUDED_DEPENDENCY_DIR");

	// Secret files (high-risk secret patterns per J5-SEC-005, J5-INV-008)
	assert.equal(engine.evaluate("credentials.json", false).reasonCode, "EXCLUDED_SECRET_PATTERN");
	assert.equal(engine.evaluate("auth.token", false).reasonCode, "EXCLUDED_SECRET_PATTERN");
	assert.equal(engine.evaluate("id_rsa", false).reasonCode, "EXCLUDED_SECRET_PATTERN");
	assert.equal(engine.evaluate("id_ed25519", false).reasonCode, "EXCLUDED_SECRET_PATTERN");
	assert.equal(engine.evaluate("server.key", false).reasonCode, "EXCLUDED_SECRET_PATTERN");
	assert.equal(engine.evaluate("cert.pem", false).reasonCode, "EXCLUDED_SECRET_PATTERN");

	// 2. .padmaignore takes precedence over .gitignore
	// keep_me.ts is negated in padmaignore even though ignored in gitignore
	const keepDecision = engine.evaluate("keep_me.ts", false);
	assert.equal(keepDecision.ignored, false);

	// ignored_by_padma.ts is ignored by rule
	const padmaDecision = engine.evaluate("ignored_by_padma.ts", false);
	assert.equal(padmaDecision.ignored, true);
	assert.equal(padmaDecision.reasonCode, "IGNORED_BY_RULE");

	// ignored_by_git.ts is ignored by git rule
	const gitDecision = engine.evaluate("ignored_by_git.ts", false);
	assert.equal(gitDecision.ignored, true);
	assert.equal(gitDecision.reasonCode, "IGNORED_BY_RULE");

	// 3. Default build directories
	assert.equal(engine.evaluate("dist/bundle.js", false).reasonCode, "BUILD_OUTPUT_ARTIFACT_ONLY");
	assert.equal(engine.evaluate("coverage/lcov.info", false).reasonCode, "BUILD_OUTPUT_ARTIFACT_ONLY");
});

test("J5-INV-002: File classification and language detection", () => {
	// Manifest
	assert.equal(classifyFile("package.json").class, "manifest");
	assert.equal(classifyFile("pnpm-workspace.yaml").class, "manifest");
	assert.equal(classifyFile("Cargo.toml").class, "manifest");

	// Config
	assert.equal(classifyFile("tsconfig.json").class, "config");
	assert.equal(classifyFile("vite.config.ts").class, "config");
	assert.equal(classifyFile("biome.json").class, "config");

	// Test
	assert.equal(classifyFile("src/auth/login.test.ts").class, "test");
	assert.equal(classifyFile("test/suite/harness.ts").class, "test");
	assert.equal(classifyFile("__tests__/utils.spec.js").class, "test");

	// Generated
	assert.equal(classifyFile("src/models.generated.ts").class, "generated");
	const genContent = new TextEncoder().encode("// @generated by compiler\nexport const x = 1;");
	assert.equal(classifyFile("src/stubs.ts", genContent).class, "generated");

	// Source
	const src = classifyFile("src/index.ts");
	assert.equal(src.class, "source");
	assert.equal(src.language, "typescript");

	const pySrc = classifyFile("scripts/worker.py");
	assert.equal(pySrc.class, "source");
	assert.equal(pySrc.language, "python");

	// Docs
	assert.equal(classifyFile("README.md").class, "docs");
	assert.equal(classifyFile("docs/architecture.mdx").class, "docs");

	// Asset & Binary
	const png = classifyFile("assets/logo.png");
	assert.equal(png.class, "asset");
	assert.equal(png.isBinary, true);

	const binaryBuf = new Uint8Array([0x48, 0x65, 0x00, 0x6c]);
	assert.equal(isBinaryBuffer(binaryBuf), true);
	assert.equal(classifyFile("data/unknown.dat", binaryBuf).isBinary, true);
});

test("J5-INV-003: Content digest computation determinism", () => {
	const content = "export function add(a: number, b: number): number { return a + b; }";
	const digest1 = computeDigest(content);
	const digest2 = computeDigest(content);
	assert.equal(digest1, digest2);
	assert.match(digest1, /^sha256:[a-f0-9]{64}$/);

	const emptyDigest = computeDigest("");
	assert.equal(emptyDigest, "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
});

test("J5-INV-004 / J5-SEC-001 / J5-SEC-002: Repository enumeration and hostile fixtures", () => {
	const testFixtureDir = join(tmpdir(), `jalacitra_inventory_test_${Date.now()}`);
	mkdirSync(testFixtureDir, { recursive: true });

	try {
		// Create normal files
		mkdirSync(join(testFixtureDir, "src"), { recursive: true });
		writeFileSync(join(testFixtureDir, "src", "index.ts"), "export const hello = 'world';");
		writeFileSync(join(testFixtureDir, "package.json"), JSON.stringify({ name: "fixture" }));

		// Create hard excluded files
		mkdirSync(join(testFixtureDir, ".git"), { recursive: true });
		writeFileSync(join(testFixtureDir, ".git", "HEAD"), "ref: refs/heads/main");
		mkdirSync(join(testFixtureDir, "node_modules", "dep"), { recursive: true });
		writeFileSync(join(testFixtureDir, "node_modules", "dep", "index.js"), "module.exports = {};");

		// Create secret file
		writeFileSync(join(testFixtureDir, "id_rsa"), "PRIVATE_KEY_DATA");

		// Create oversized file (> 100 bytes with limit 100 bytes)
		writeFileSync(join(testFixtureDir, "src", "large.ts"), "A".repeat(200));

		// Run enumeration with maxFileSize = 150 bytes
		const result = enumerateRepository(testFixtureDir, { maxFileSize: 150 });

		// Verify files indexed
		const paths = result.files.map((f) => f.path);
		assert.ok(paths.includes("src/index.ts"));
		assert.ok(paths.includes("package.json"));
		assert.ok(paths.includes("src/large.ts"));

		// Large file has skipReason FILE_TOO_LARGE
		const largeFile = result.files.find((f) => f.path === "src/large.ts");
		assert.equal(largeFile?.skipReason, "FILE_TOO_LARGE");

		// Verify excluded files
		const skippedReasons = result.skippedFiles.map((s) => s.reasonCode);
		assert.ok(skippedReasons.includes("EXCLUDED_VCS_INTERNAL") || skippedReasons.includes("EXCLUDED_DEPENDENCY_DIR"));
		assert.ok(skippedReasons.includes("EXCLUDED_SECRET_PATTERN"));
		assert.ok(skippedReasons.includes("FILE_TOO_LARGE"));

		// Verify secret file is NEVER indexed in result.files
		assert.equal(paths.includes("id_rsa"), false);
		assert.equal(paths.includes(".git/HEAD"), false);
		assert.equal(paths.includes("node_modules/dep/index.js"), false);
	} finally {
		rmSync(testFixtureDir, { recursive: true, force: true });
	}
});
