// Jālacitra File Classification and Language Detection (Part F, J5-INV-001 through J5-INV-007)

import { extname } from "node:path";
import type { FileClass } from "../model/nodes.ts";

export interface ClassificationResult {
	language: string | null;
	class: FileClass;
	isBinary: boolean;
	declarationFile?: boolean;
}

const EXT_TO_LANGUAGE: Record<string, string> = {
	".ts": "typescript",
	".tsx": "typescript",
	".mts": "typescript",
	".cts": "typescript",
	".d.ts": "typescript",
	".js": "javascript",
	".jsx": "javascript",
	".mjs": "javascript",
	".cjs": "javascript",
	".json": "json",
	".jsonc": "json",
	".json5": "json",
	".yaml": "yaml",
	".yml": "yaml",
	".toml": "toml",
	".md": "markdown",
	".mdx": "markdown",
	".py": "python",
	".pyi": "python",
	".go": "go",
	".rs": "rust",
	".java": "java",
	".c": "c",
	".cpp": "cpp",
	".h": "c",
	".hpp": "cpp",
	".cs": "csharp",
	".rb": "ruby",
	".php": "php",
	".sh": "shell",
	".bash": "shell",
	".ps1": "powershell",
	".sql": "sql",
	".html": "html",
	".css": "css",
	".scss": "scss",
	".xml": "xml",
};

const BINARY_EXTENSIONS = new Set([
	".png",
	".jpg",
	".jpeg",
	".gif",
	".ico",
	".webp",
	".bmp",
	".pdf",
	".wasm",
	".node",
	".exe",
	".dll",
	".so",
	".dylib",
	".zip",
	".tar",
	".gz",
	".tgz",
	".woff",
	".woff2",
	".ttf",
	".eot",
	".mp3",
	".mp4",
	".mov",
	".avi",
]);

const MANIFEST_FILENAMES = new Set([
	"package.json",
	"package-lock.json",
	"pnpm-lock.yaml",
	"pnpm-workspace.yaml",
	"yarn.lock",
	"cargo.toml",
	"cargo.lock",
	"go.mod",
	"go.sum",
	"pyproject.toml",
	"poetry.lock",
	"requirements.txt",
	"gemfile",
	"composer.json",
	"pom.xml",
	"build.gradle",
]);

export function isBinaryBuffer(buf: Uint8Array): boolean {
	// Check first 4096 bytes for NUL byte
	const checkLen = Math.min(buf.length, 4096);
	for (let i = 0; i < checkLen; i++) {
		if (buf[i] === 0) {
			return true;
		}
	}
	return false;
}

export function classifyFile(repoRelativePath: string, contentSnippet?: Uint8Array): ClassificationResult {
	const lowerPath = repoRelativePath.toLowerCase();
	const baseName = lowerPath.split("/").pop() ?? "";
	const ext = extname(lowerPath);

	const isKnownBinary = BINARY_EXTENSIONS.has(ext);
	const isBinary = isKnownBinary || (contentSnippet ? isBinaryBuffer(contentSnippet) : false);

	if (isBinary) {
		return {
			language: null,
			class: "asset",
			isBinary: true,
		};
	}

	const isDeclaration = lowerPath.endsWith(".d.ts") || lowerPath.endsWith(".d.mts") || lowerPath.endsWith(".d.cts");

	let language: string | null = EXT_TO_LANGUAGE[ext] ?? null;
	if (isDeclaration) {
		language = "typescript";
	}

	// 1. Manifest
	if (MANIFEST_FILENAMES.has(baseName)) {
		return {
			language,
			class: "manifest",
			isBinary: false,
		};
	}

	// 2. Vendored
	if (lowerPath.startsWith("vendor/") || lowerPath.startsWith("third_party/")) {
		return {
			language,
			class: "vendored",
			isBinary: false,
		};
	}

	// 3. Test
	const isTestPath =
		lowerPath.startsWith("test/") ||
		lowerPath.startsWith("tests/") ||
		lowerPath.startsWith("testing/") ||
		lowerPath.startsWith("__tests__/") ||
		lowerPath.includes("/test/") ||
		lowerPath.includes("/tests/") ||
		lowerPath.includes("/testing/") ||
		lowerPath.includes("/__tests__/") ||
		baseName.includes(".test.") ||
		baseName.includes(".spec.");

	if (isTestPath) {
		return {
			language,
			class: "test",
			isBinary: false,
			declarationFile: isDeclaration,
		};
	}

	// 4. Config
	const isConfig =
		baseName.includes(".config.") ||
		baseName.startsWith("tsconfig") ||
		baseName === "biome.json" ||
		baseName.startsWith(".eslintrc") ||
		baseName.startsWith(".prettierrc") ||
		baseName === "dockerfile" ||
		baseName === "makefile" ||
		baseName.startsWith(".env");

	if (isConfig) {
		return {
			language,
			class: "config",
			isBinary: false,
		};
	}

	// 5. Generated
	const isGeneratedName =
		baseName.includes(".generated.") ||
		baseName.endsWith(".g.ts") ||
		baseName.includes(".pb.") ||
		baseName.startsWith("openapi.");

	let hasGeneratedHeader = false;
	if (contentSnippet && contentSnippet.length > 0) {
		const head = new TextDecoder().decode(contentSnippet.slice(0, 512));
		if (head.includes("@generated") || head.includes("AUTO-GENERATED") || head.includes("Code generated by")) {
			hasGeneratedHeader = true;
		}
	}

	if (isGeneratedName || hasGeneratedHeader) {
		return {
			language,
			class: "generated",
			isBinary: false,
			declarationFile: isDeclaration,
		};
	}

	// 6. Docs
	if (ext === ".md" || ext === ".mdx" || ext === ".rst" || ext === ".txt" || lowerPath.startsWith("docs/")) {
		return {
			language,
			class: "docs",
			isBinary: false,
		};
	}

	// 7. Source
	if (
		language === "typescript" ||
		language === "javascript" ||
		language === "python" ||
		language === "go" ||
		language === "rust" ||
		language === "c" ||
		language === "cpp" ||
		language === "java" ||
		language === "csharp" ||
		language === "ruby" ||
		language === "php" ||
		language === "shell" ||
		language === "powershell" ||
		language === "sql" ||
		language === "html" ||
		language === "css" ||
		language === "scss"
	) {
		return {
			language,
			class: "source",
			isBinary: false,
			declarationFile: isDeclaration,
		};
	}

	return {
		language,
		class: "other",
		isBinary: false,
	};
}
