/** 50 funny developer quotes featuring Padma's Sanskrit vocabulary with English glosses. */
export const PADMA_TAGLINES: readonly string[] = [
	'"The praśna [prompt] is yours — please do not ask me to rewrite your entire backend in Rust at 2 AM."',
	'"What’s broken on your side of the kīlaphālaka [keyboard]? Please don’t say ’everything’."',
	'"Look at this truṭi [bug]: written at 3:00 AM, fueled purely by caffeine and poor life choices."',
	'"Pushing to main without anumati [permission] at 4:59 PM on a Friday? Bold move, legend."',
	'"Searching the smṛtikoṣa [memory vault] for that one bash command I’ve Googled four hundred times."',
	'"The parīkṣā [test suite] passed on the first run. Do not touch anything, do not breathe, just back away slowly."',
	'"Deleting 500 lines of legacy spaghetti is the closest a developer ever gets to mokṣa [liberation]."',
	'"Entering deep dhyāna [thinking]... which mostly means staring at the screen wondering why CSS won’t center this div."',
	'"Behold the classic māyā [illusion]: ‘Trust me, this quick refactor will only take five minutes.’"',
	'"Checking the pramāṇa [evidence] before git push: did I just commit my production .env file and AWS keys?"',
	'"The yantra [tool execution] worked on localhost, so legally it’s an infrastructure problem now."',
	'"One does not simply merge into main without four rounds of desperate punar-sandhāna [retry]."',
	'"Consulting the jālacitra [code graph] to see who wrote this awful code (git blame says: Me, last Tuesday)."',
	'"The koṣa [token budget] is bleeding out, and the regex still matches literally everything except what you want."',
	'"Feed the sandhāna [execution loop] good prompts, or prepare to explain the prod outage to your VP."',
	'"Deep dhyāna [reasoning] in progress... please don’t ping me on Slack asking for an ETA."',
	'"No vikalpa [hypothesis] survives first contact with a user clicking the submit button 47 times in a row."',
	'"May your siddhi [verified completion] land before your third iced coffee melts into bitter disappointment."',
	'"A true senior engineer checks the niyamapatra [rulebook] only after staging is actively on fire."',
	'"Running the parīkṣā [unit tests] and whispering gentle Vedic prayers to the GitHub Actions runner."',
	'"The kāryasūcī [task list] is infinite, Jira is down, and my remaining patience is strictly single-threaded."',
	'"Adding console.log(’HERE 1’, ’HERE 2’, ’WHY GOD WHY’): the highest form of pratikriyā [feedback]."',
	'"Beware the infinite saṃsāra [endless cycle] hiding inside a while(true) loop with a broken exit condition."',
	'"The lakṣya [goal] was a quick shell script; three days later we have an over-engineered distributed microservice."',
	'"Checking the smṛtikoṣa [memory cache] — yes, that ’// TODO: fix this hack later’ has been there since 2018."',
	'"The sandhāna [session] is live! Please don’t run sudo rm -rf / just to see what happens."',
	'"Behold the sūkṣmaśastra [surgical diff]: 1 line changed, 43 files broken, pure poetry."',
	'"Every git śākhā [branch] is just a cry for help waiting for an LGTM that never comes."',
	'"A merge conflict in package-lock.json is the universe testing your śānti [inner peace]."',
	'"Checking the stambhamāna [stuck detector] because this Promise has been pending since last sprint."',
	'"Turning stale coffee into bug reports and questionable ājñā [commands] since 9:00 AM."',
	'"The sārasaṅgraha [compacted context] is tidy, but your architectural technical debt will outlive us all."',
	'"Speak your praśna [prompt], dev, before the API rate limit smites our entire team."',
	'"Trust the nyāya [deterministic logic], even when ’z-index: 9999999’ is your only remaining CSS solution."',
	'"Ready your kṣepaṇa [action]: let’s ship this completely untested hotfix straight to production!"',
	'"My dhyāna [thinking] buffer is full, but the developer has wandered off to make another cup of coffee."',
	'"Why optimize the algorithm when you can just throw more AWS credits at the restless citta [mind]?"',
	'"It’s not a truṭi [bug] — it’s an undocumented, highly spontaneous surprise feature."',
	'"Checking the pramāṇapatra [official documentation] as an absolute last resort after four hours of blind guessing."',
	'"Contemplating the cosmic śūnya [null pointer] that just took down three production availability zones."',
	'"Your ājñā [command] is my sacred loop. Please tell me you didn’t copy-paste this from 2011 Stack Overflow."',
	'"Summoning the chāyāhasta [ghost hand] to touch legacy code that has been running on dark magic since 2014."',
	'"Align your saṅkalpa [intent] before the linter obliterates your self-esteem with 84 red squiggles."',
	'"The parīkṣā [test suite] failed successfully — at least we know the CI runner isn’t sleeping on the job."',
	'"Punar-sandhāna [retry] attempt 73: maybe running the exact same command one more time will magically fix it."',
	'"The padma [lotus] blooms even in the darkest, most terrifying legacy callback hell."',
	'"May your build be swift, your node_modules be lightweight, and your śākhā [branch] merges conflict-free."',
	'"A single missing semicolon is the root cause of all cosmic and mortal duḥkha [suffering]."',
	'"Your keystrokes are recorded in the grantha [immutable ledger] — so think twice before writing ’temp_fix_final_v2’."',
	'"True developer enlightenment is seeing zero truṭi [errors] on npm run check on the very first try."',
];

/** Explicit styling also works in terminals where Chalk\'s color detection is disabled. */
export function getFormattedTagline(index = Math.floor(Math.random() * PADMA_TAGLINES.length)): string {
	const selected = Number.isInteger(index) && index >= 0 && index < PADMA_TAGLINES.length ? index : 0;
	return `\x1b[1m\x1b[38;2;215;201;184m${PADMA_TAGLINES[selected]}\x1b[39m\x1b[22m`;
}
