import type { ThinkingLevel } from "@anvaya.sh/padma-agent-core";

/** Display vocabulary. Protocol identifiers and provider/model names stay unchanged. */
export const THINKING_LABELS: Record<ThinkingLevel, string> = {
	off: "Virāma [off]",
	minimal: "Svalpa [minimal]",
	low: "Laghu [low]",
	medium: "Madhyama [medium]",
	high: "Gambhīra [high]",
	xhigh: "Atigambhīra [extra high]",
	max: "Parama [maximum]",
};

export function normalizeSanskrit(value: string): string {
	return value.normalize("NFD").replace(/\p{M}/gu, "").toLowerCase();
}

export function resolveThinkingLevel(value: string): ThinkingLevel | undefined {
	const normalized = normalizeSanskrit(value.trim());
	return (Object.keys(THINKING_LABELS) as ThinkingLevel[]).find(
		(level) => level === normalized || normalizeSanskrit(THINKING_LABELS[level].split(" ")[0]) === normalized,
	);
}

const UI_LABELS: Readonly<Record<string, string>> = {
	"Trust project folder?": "Viśvāsa [trust project folder]?",
	"Project trust": "Viśvāsa [project trust]",
	Trust: "Viśvāsa [trust]",
	"Trust (this session only)": "Viśvāsa [trust this session only]",
	"Do not trust": "Aviśvāsa [do not trust]",
	"Do not trust (this session only)": "Aviśvāsa [do not trust this session]",
	trusted: "Viśvasta [trusted]",
	untrusted: "Aviśvasta [untrusted]",
	Yes: "Ām [yes]",
	No: "Na [no]",
	navigate: "Gamana [navigate]",
	select: "Cayana [select]",
	save: "Rakṣaṇa [save]",
	cancel: "Virāma [cancel]",
	close: "Samāpana [close]",
	"to expand": "Vistāra [to expand]",
	read: "Paṭhana [read]",
	write: "Lekhana [write]",
	edit: "Saṃśodhana [edit]",
	grep: "Anveṣaṇa [grep]",
	find: "Mārga-anveṣaṇa [find]",
	ls: "Sūcī [ls]",
	docs: "Śāstra [docs]",
	resource: "Sādhana [resource]",
	bash: "Ājñā [bash]",
	powershell: "Ājñā [PowerShell]",
	"Auto-compact": "Svayaṃ-saṅgraha [auto compact]",
	"Steering mode": "Diśā [steering mode]",
	"Follow-up mode": "Anugamana [follow-up mode]",
	Transport: "Vāhana [transport]",
	"HTTP idle timeout": "Kālasīmā [HTTP idle timeout]",
	"Cache warming": "Smṛti-sajjatā [cache warming]",
	"Hide thinking": "Dhyāna-gopana [hide thinking]",
	"Mermaid diagrams": "Citra [Mermaid diagrams]",
	"Cache miss notices": "Smṛti-sūcanā [cache miss notices]",
	"Collapse changelog": "Vṛttānta-saṅkoca [collapse changelog]",
	"Quiet startup": "Śānta-ārambha [quiet startup]",
	"Install telemetry": "Sthāpana-māpana [install telemetry]",
	"Default project trust": "Mūla-viśvāsa [default project trust]",
	"Double-escape action": "Dvi-virāma [double Escape action]",
	"Tree filter": "Vaṃśa-chānana [tree filter]",
	"Tree filter mode": "Vaṃśa-chānana [tree filter mode]",
	"Hardware cursor": "Sūcaka [hardware cursor]",
	"Show hardware cursor": "Sūcaka [show hardware cursor]",
	"Editor padding": "Lekhaka-antarāla [editor padding]",
	"Output padding": "Phala-antarāla [output padding]",
	"Autocomplete items": "Pūrti-saṅkhyā [autocomplete items]",
	"Autocomplete max visible": "Pūrti-saṅkhyā [visible suggestions]",
	"Clear on shrink": "Saṅkoca-śodhana [clear on shrink]",
	"Terminal progress": "Pragati [terminal progress]",
	"Show terminal progress": "Pragati [show terminal progress]",
	"TUI mode": "Darśana [TUI mode]",
	"Fullscreen exit output": "Prasthāna-phala [exit output]",
	"Fullscreen scrollbar": "Pāṭha-sūcaka [fullscreen scrollbar]",
	"Fullscreen copy on select": "Cayana-pratilipi [copy on select]",
	"Fullscreen wheel scroll": "Cakra-gamana [wheel scroll]",
	"Fullscreen wheel scroll lines": "Cakra-gamana [wheel scroll lines]",
	"Show images": "Citra-darśana [show images]",
	"Image width": "Citra-vistāra [image width]",
	"Image width (cells)": "Citra-vistāra [image width in cells]",
	"Auto-resize images": "Citra-parimāṇa [auto resize images]",
	"Block images": "Citra-nirodha [block images]",
	"Enable skill commands": "Kauśala-ājñā [skill commands]",
	"Skill commands": "Kauśala-ājñā [skill commands]",
	"Thinking level": "Dhyāna [thinking level]",
	"Default thinking level": "Mūla-dhyāna [default thinking]",
	"Default thinking level per model": "Dhyāna [model defaults]",
	"Per-Model Thinking Level": "Dhyāna [model defaults]",
	"Fullscreen wheel scrolling": "Cakra-gamana [wheel scrolling]",
	"Autocomplete max items": "Pūrti-sīmā [suggestion limit]",
	"Model thinking levels": "Dhyāna [model thinking levels]",
	"Per-model thinking": "Pratimāna-dhyāna [per-model thinking]",
	"Default model": "Mūla-pratimāna [default model]",
	Theme: "Varṇayojanā [theme]",
	"Light theme": "Prakāśa [light theme]",
	"Dark theme": "Tamas [dark theme]",
	"Light Theme": "Prakāśa [light theme]",
	"Dark Theme": "Tamas [dark theme]",
	"Automatic Theme": "Svayaṃ-varṇa [automatic theme]",
	"Change mode": "Rīti-parivartana [change mode]",
	Apply: "Prayoga [apply]",
	Warnings: "Sāvadhāna [warnings]",
	"Anthropic extra usage": "Anthropic atirikta-vyaya [extra usage]",
	Ask: "Praśna [ask]",
	"Always trust": "Sadā-viśvāsa [always trust]",
	"Never trust": "Aviśvāsa [never trust]",
	true: "Sakriya [enabled]",
	false: "Niṣkriya [disabled]",
	all: "Sarva [all]",
	"one-at-a-time": "Ekaśaḥ [one at a time]",
	default: "Mūla [default]",
	current: "Vartamāna [current]",
	none: "Śūnya [none]",
	auto: "Svayam [automatic]",
	automatic: "Svayam [automatic]",
	off: "Virāma [off]",
	regular: "Sādhāraṇa [regular]",
	fullscreen: "Pūrṇapaṭa [fullscreen]",
	transcript: "Saṃvāda [transcript]",
	tree: "Vaṃśa [session tree]",
	fork: "Śākhā [fork]",
	"no-tools": "Ayantra [no tools]",
	"user-only": "Kevala-prayoktṛ [user only]",
	"labeled-only": "Cihnita [labeled only]",
	on: "Sakriya [enabled]",
	always: "Sadā [always]",
	ask: "Praśna [ask]",
	never: "Kadāpi-na [never]",
	"save and go back": "Rakṣaṇa [save and return]",
	"switch to single theme": "Eka-varṇa [single theme]",
};

/** Translate presentation text only; values submitted to handlers remain machine identifiers. */
export function uiLabel(label: string): string {
	if (label.startsWith("Trust parent folder (")) {
		return `Pitṛ-viśvāsa [trust parent folder] ${label.slice("Trust parent folder ".length)}`;
	}
	return UI_LABELS[label] ?? label;
}
